services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"

    kong:
        container_name: kong
        image: kong:latest
        volumes:
        - ./kong/kong.conf:/etc/kong/kong.conf
        ports: